# Copyright 2026 scarryhott/bio contributors.
"""Closure-native AGI kernel, RND1 integration, and biological coevolution."""

from .biology import (
    BIOLOGICAL_RELATIONS,
    BiologicalEpisode,
    BiologicalPerspective,
    CoevolutionCarrier,
    biological_act_path,
    biological_episode_to_carrier,
    resolution_from_biological_return,
    shadow_cannot_certify,
    to_potential_gate,
)
from .connected_return import (
    ConnectedReturnVerdict,
    LabeledOccurrence,
    LocalCell,
    evaluate_connected_return,
    make_occurrence,
)
from .derived_topologies import (
    DERIVED_TOPOLOGY_IDS,
    DERIVED_TOPOLOGY_SPECS,
    DerivedTopologySpec,
    ball_hair_topology,
    biological_nonidentical_topology,
    closure_chaitin_topology,
    fold_glue_topology,
    kakeya_contact_topology,
    partition_curvature_topology,
    rotation_extension_topology,
    self_limit_topology,
    topos_turing_topology,
    zero_infinity_topology,
)
from .digest import digest, interaction_digest, partition_curvature_digest
from .goel_operator import (
    DualClosureBindingReceipt,
    GOEL_PROVENANCE,
    GoelChaitinOperatorReceipt,
    GoelDNAEnvironmentState,
    GoelOperatorStatus,
    GoelProvenance,
    PolymeraseMode,
    TokenizedRelativityBall,
    apply_goel_chaitin_operator,
    bind_local_kakeya_global_goel,
    goel_state_from_modalities,
    infer_polymerase_mode,
    programme_role_split,
    to_external_biological_hair,
    to_return_witness,
    tokenized_relativity_ball_from_cells,
)
from .hair import build_holistic_hair
from .independent_model import (
    Admission,
    ArchitecturalLoopTurn,
    ArchitecturalUnity,
    ClosureBackComparison,
    ClosureLoopMemory,
    IndependentEvaluation,
    InterfaceProjection,
    InterfaceValueError,
    LoopInvariant,
    OpaqueAction,
    OpaqueConfiguration,
    ProvisionalProjection,
    UnifiedClosureArchitecturalLoop,
    canonical_json,
    canonical_value,
    stable_digest,
)
from .ivi_structure import (
    STRUCTURE_MAP_PATH,
    CoreStructure,
    IVILevel,
    core_structures,
    ivi_ladder,
    load_structure_map,
    ownership_declaration,
    predual_pairs,
    spine_digest,
    thesis_statement,
)
from .return_unified_runtime import (
    OpenArchitectureCarrier,
    ReturnUnifiedEpisodeSpec,
    ReunifiedAdmissionReceipt,
    architecture_from_system,
    episode_from_record,
    load_finite_bio_episodes,
    probe_weights_available,
    receipt_to_dict,
    reunify_episode,
)
from .runtime import ClosureRuntime
from .tagtokn_bridge import (
    TagtoknClosureReceipt,
    TagtoknReturnStatus,
    classify_turn,
    framework_compatibility,
    to_tagtokn_receipt,
)
from .topology import (
    ADMISSIBLE_TOPOLOGIES,
    UNIFIED_AXIOMETRY_MOTIFS,
    DerivationMotif,
    UnifiedAxiometry,
    VerificationTopology,
    admit_verification_topology,
    assert_admissible,
    construct_next_topos,
    default_admissibility_policy,
    topology_to_gate,
)
from .types import (
    ClosureCarrier,
    ClosureConfig,
    ClosureMode,
    ClosureReceipt,
    HairComposition,
    HairSource,
    MicroAction,
    PotentialGate,
    Resolution,
    ReturnWitness,
    StepAdmission,
)

__all__ = [
    "ADMISSIBLE_TOPOLOGIES",
    "Admission",
    "ArchitecturalLoopTurn",
    "ArchitecturalUnity",
    "BIOLOGICAL_RELATIONS",
    "BiologicalEpisode",
    "BiologicalPerspective",
    "ClosureBackComparison",
    "ClosureCarrier",
    "ClosureConfig",
    "ClosureLoopMemory",
    "ClosureMode",
    "ClosureReceipt",
    "ClosureRuntime",
    "CoevolutionCarrier",
    "ConnectedReturnVerdict",
    "DERIVED_TOPOLOGY_IDS",
    "DERIVED_TOPOLOGY_SPECS",
    "DerivedTopologySpec",
    "DerivationMotif",
    "GoelChaitinOperatorReceipt",
    "GoelDNAEnvironmentState",
    "GoelOperatorStatus",
    "GoelProvenance",
    "GOEL_PROVENANCE",
    "DualClosureBindingReceipt",
    "HairComposition",
    "HairSource",
    "IndependentEvaluation",
    "InterfaceProjection",
    "InterfaceValueError",
    "IVILevel",
    "LabeledOccurrence",
    "LocalCell",
    "LoopInvariant",
    "MicroAction",
    "OpaqueAction",
    "OpaqueConfiguration",
    "OpenArchitectureCarrier",
    "PolymeraseMode",
    "PotentialGate",
    "ProvisionalProjection",
    "ReunifiedAdmissionReceipt",
    "Resolution",
    "ReturnUnifiedEpisodeSpec",
    "ReturnWitness",
    "STRUCTURE_MAP_PATH",
    "StepAdmission",
    "TagtoknClosureReceipt",
    "TagtoknReturnStatus",
    "TokenizedRelativityBall",
    "UNIFIED_AXIOMETRY_MOTIFS",
    "UnifiedAxiometry",
    "UnifiedClosureArchitecturalLoop",
    "VerificationTopology",
    "admit_verification_topology",
    "apply_goel_chaitin_operator",
    "architecture_from_system",
    "assert_admissible",
    "ball_hair_topology",
    "bind_local_kakeya_global_goel",
    "biological_act_path",
    "biological_episode_to_carrier",
    "biological_nonidentical_topology",
    "build_holistic_hair",
    "canonical_json",
    "canonical_value",
    "classify_turn",
    "closure_chaitin_topology",
    "construct_next_topos",
    "core_structures",
    "default_admissibility_policy",
    "digest",
    "episode_from_record",
    "evaluate_connected_return",
    "fold_glue_topology",
    "framework_compatibility",
    "goel_state_from_modalities",
    "infer_polymerase_mode",
    "interaction_digest",
    "ivi_ladder",
    "kakeya_contact_topology",
    "load_finite_bio_episodes",
    "load_structure_map",
    "make_occurrence",
    "ownership_declaration",
    "partition_curvature_digest",
    "partition_curvature_topology",
    "predual_pairs",
    "probe_weights_available",
    "programme_role_split",
    "receipt_to_dict",
    "resolution_from_biological_return",
    "reunify_episode",
    "rotation_extension_topology",
    "self_limit_topology",
    "shadow_cannot_certify",
    "spine_digest",
    "stable_digest",
    "thesis_statement",
    "to_external_biological_hair",
    "to_potential_gate",
    "to_return_witness",
    "to_tagtokn_receipt",
    "tokenized_relativity_ball_from_cells",
    "topology_to_gate",
    "topos_turing_topology",
    "zero_infinity_topology",
]

try:
    from .rnd_controller import TokenAdmission, closure_token_admission
    from .sampler_bridge import admit_denoising_step, baseline_unmask_mask, make_carrier
except ImportError:  # pragma: no cover
    TokenAdmission = None
    closure_token_admission = None
    admit_denoising_step = None
    baseline_unmask_mask = None
    make_carrier = None
else:
    __all__.extend(
        [
            "TokenAdmission",
            "closure_token_admission",
            "admit_denoising_step",
            "baseline_unmask_mask",
            "make_carrier",
        ]
    )