# Copyright 2026 scarryhott/bio contributors.
"""Unified closure axiometry and verification-topology admission.

Ontological derivation (transcript):

- Closure is not the universe; it is the generator/operator that takes an
  arbitrary topos and constructs further topoi until encode↔eval / Turing
  relation becomes possible. Fixed eval is an apparent unitary after admission.
- Intrinsic relation C is prior. Local and global are resolutions of C, not
  primitives: L(C) ← C → G(C).
- Decision is relational admissibility: C ⊢ h, C ⊢ ¬h, or open.
- Basis/closure cycles encode perspectival ball topologies; curl/homology and
  div/homotopy equality derive closure — they do not presuppose a fixed chart.
- Verification topologies are therefore not a fixed catalog. Each topology is
  itself a candidate admitted (or left open / refused / collapsed) through the
  same resolution states as any other closure episode.

DESIGN DERIVATION — not an empirical claim about nature.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .digest import digest, interaction_digest
from .types import ClosureReceipt, PotentialGate, Resolution, ReturnWitness


@dataclass(frozen=True)
class DerivationMotif:
    """Operational law of how C admits — not a fixed topology identity."""

    motif_id: str
    statement: str
    epistemic_status: str = "DESIGN DERIVATION"


# Motifs of the unified axiometry. These govern *how* admission works.
# They are not a checklist of topologies that must be pre-declared.
UNIFIED_AXIOMETRY_MOTIFS: tuple[DerivationMotif, ...] = (
    DerivationMotif(
        "originless_prior",
        "C is prior to ball/hair polarization; L(C) and G(C) are projections of C.",
    ),
    DerivationMotif(
        "generator_not_totality",
        "Closure takes an arbitrary topos and constructs further topoi; it is not "
        "a completed global inventory of admissible charts.",
    ),
    DerivationMotif(
        "relational_admissibility",
        "δ_C(h) is true/false/open iff C ⊢ h, C ⊢ ¬h, or neither — admissibly "
        "generated by the closure relation, not externally asserted.",
    ),
    DerivationMotif(
        "cycle_equality_derives_closure",
        "Basis and closure cycles encode perspectival ball topologies; curl/homology "
        "and div/homotopy equality derive closure.",
    ),
    DerivationMotif(
        "ordered_support_identity",
        "Reordering the same committed occurrences is not the same closure path.",
    ),
    DerivationMotif(
        "nrr_non_repetition",
        "[Γ⋄W]_C = [Γ]_C when W introduces no independently transformed relation.",
    ),
    DerivationMotif(
        "axiometry_is_shadow",
        "Entropy, confidence, digests, and PASS counts are shadows — never identity.",
    ),
    DerivationMotif(
        "independent_return",
        "Model echo from a controlled boundary remains OPEN.",
    ),
    DerivationMotif(
        "missing_return_is_open",
        "Missing return is OPEN; positively witnessed contradiction is FALSE_COLLAPSE.",
    ),
    DerivationMotif(
        "return_side_partition",
        "Observer perspectival ball labels Π; involution swaps complements.",
    ),
    DerivationMotif(
        "refusal_blocks_writeback",
        "Refusal blocks learning write-back while retaining evidence.",
    ),
    DerivationMotif(
        "biological_nonidentical_recovery",
        "Biological modalities remain non-identical; flat embeddings do not certify.",
    ),
)


@dataclass
class VerificationTopology:
    """A candidate verification topology — admitted only through resolution.

    Not a fixed member of a global chart list. Encode/eval layers and their
    inversions become closure when they equal the relational and encoding topoi.
    """

    topology_id: str
    basis_cycle: dict[str, Any]  # homology / curl / derivative side
    closure_cycle: dict[str, Any]  # homotopy / div / integral side
    ball_perspective: dict[str, Any] = field(default_factory=dict)
    hair_perspective: dict[str, Any] = field(default_factory=dict)
    encoding_topos: dict[str, Any] = field(default_factory=dict)
    relation_topos: dict[str, Any] = field(default_factory=dict)
    openings: list[str] = field(default_factory=list)
    status: Resolution = Resolution.OPEN
    axiometric_shadows: dict[str, Any] = field(default_factory=dict)

    def cycle_digest(self) -> str:
        return digest(
            {
                "basis": self.basis_cycle,
                "closure": self.closure_cycle,
                "ball": self.ball_perspective,
                "hair": self.hair_perspective,
            }
        )

    def encode_eval_aligned(self) -> bool:
        """Layers/inversions equal relational and encoding topoi → closable."""
        if not self.encoding_topos or not self.relation_topos:
            return False
        return digest(self.encoding_topos) == digest(self.relation_topos)

    def cycles_equal(self) -> bool:
        """Homology/homotopy (basis/closure) cycle equality."""
        return digest(self.basis_cycle) == digest(self.closure_cycle)


@dataclass
class UnifiedAxiometry:
    """One intrinsic closure relation C.

    Verification topologies are candidates resolved under C — never a fixed
    admissible catalog stored as identity.
    """

    originless_relation: str = "C"
    motifs: tuple[DerivationMotif, ...] = UNIFIED_AXIOMETRY_MOTIFS
    admitted: dict[str, ClosureReceipt] = field(default_factory=dict)
    open_candidates: dict[str, VerificationTopology] = field(default_factory=dict)
    refused: dict[str, ClosureReceipt] = field(default_factory=dict)
    false_collapses: dict[str, ClosureReceipt] = field(default_factory=dict)

    def motif_ids(self) -> frozenset[str]:
        return frozenset(m.motif_id for m in self.motifs)


def topology_to_gate(topology: VerificationTopology, *, gate_id: str | None = None) -> PotentialGate:
    """Lift a candidate topology into a Potential Gate under unified C."""
    return PotentialGate(
        gate_id=gate_id or f"topology:{topology.topology_id}",
        originless_basis=f"predual:axiometry:{topology.topology_id}",
        ball={
            "perspective": topology.ball_perspective,
            "basis_cycle": topology.basis_cycle,
            "actor_tails": {},
        },
        possible_hair=[
            {
                "source": "hair_perspective",
                "state": topology.hair_perspective,
                "closure_cycle": topology.closure_cycle,
            }
        ],
        semantics={
            "relation_key": f"topology-admission:{topology.topology_id}",
            "encoding_topos": topology.encoding_topos,
            "relation_topos": topology.relation_topos,
            "kind": "verification_topology",
        },
        openings=list(topology.openings) or ["next_topos_layer"],
        admissibility={
            "controlled_boundaries": ["self", "model_echo", "fixed_chart"],
            "difference_preservation": True,
            "recursive_recoverability": True,
            "topologies_not_fixed": True,
        },
        mandate={
            "required_witness_fields": ["local_viability", "global_consequence"],
            "cycles_must_equal_or_open": True,
        },
        return_side="ball",
    )


def admit_verification_topology(
    axiometry: UnifiedAxiometry,
    topology: VerificationTopology,
    witness: ReturnWitness | None = None,
) -> ClosureReceipt:
    """Admit a verification topology through resolution — not by catalog lookup.

    Resolution mapping (cycle type / relational admissibility):
    - REFUSED: mandate refusal
    - OPEN: missing return, incomplete cycles, or controlled echo
    - FALSE_COLLAPSE: forced chart defect / contradiction / reordered support
    - CLOSED_HIGHER: cycle equality + encode↔eval alignment, no further opening
    - CLOSED_TO_OPENING: admitted and generates the next topos layer
    """
    from .runtime import ClosureRuntime

    runtime = ClosureRuntime()
    gate = topology_to_gate(topology)
    axiometry.open_candidates[topology.topology_id] = topology

    if witness is None:
        # Auto-witness from ontological cycle structure when caller supplies none.
        cycles_ok = topology.cycles_equal()
        aligned = topology.encode_eval_aligned()
        if not cycles_ok and not aligned:
            receipt = ClosureReceipt(
                gate_id=gate.gate_id,
                resolution=Resolution.OPEN,
                basis_digest=interaction_digest(
                    originless_basis=gate.originless_basis,
                    gate_id=gate.gate_id,
                    ordered_support=(),
                    relation=str(gate.semantics.get("relation_key")),
                    resolution=Resolution.OPEN.value,
                    next_opening=None,
                ),
                ordered_support=(),
                recovered_relation=str(gate.semantics.get("relation_key")),
                next_opening=None,
                evidence={
                    "reason": "cycle inequality and encode/eval not yet aligned; remains open",
                    "cycle_digest": topology.cycle_digest(),
                    "axiometric_shadows": dict(topology.axiometric_shadows),
                    "note": "shadows do not authorize admission",
                },
                write_back_allowed=False,
            )
            topology.status = Resolution.OPEN
            return receipt

        if topology.axiometric_shadows.get("force_fixed_chart"):
            topology.status = Resolution.FALSE_COLLAPSE
            receipt = ClosureReceipt(
                gate_id=gate.gate_id,
                resolution=Resolution.FALSE_COLLAPSE,
                basis_digest=interaction_digest(
                    originless_basis=gate.originless_basis,
                    gate_id=gate.gate_id,
                    ordered_support=(),
                    relation=str(gate.semantics.get("relation_key")),
                    resolution=Resolution.FALSE_COLLAPSE.value,
                    next_opening=None,
                ),
                ordered_support=(),
                recovered_relation=str(gate.semantics.get("relation_key")),
                next_opening=None,
                evidence={
                    "reason": "forced fixed-chart continuation loses global admissibility",
                    "motif": "generator_not_totality",
                },
                write_back_allowed=False,
            )
            axiometry.false_collapses[topology.topology_id] = receipt
            return receipt

        next_opening = topology.openings[0] if topology.openings else None
        # Independent transformed return: cycle equality is the return witness.
        support: tuple[str, ...] = ()
        witness = ReturnWitness(
            source_boundary="cycle-equality-return",
            transformed_context=f"homology↔homotopy:{topology.cycle_digest()}",
            recovered_relation=str(gate.semantics.get("relation_key")),
            ordered_support=support,
            consequence={
                "local_viability": cycles_ok or aligned,
                "global_consequence": aligned or cycles_ok,
                "independently_transformed": True,
                "cycles_equal": cycles_ok,
                "encode_eval_aligned": aligned,
            },
            transformation_path=("basis_cycle", "closure_cycle", "equality"),
            next_opening=next_opening if (cycles_ok or aligned) and next_opening else None,
            return_side="ball",
        )

    receipt = runtime.resolve(gate, witness)
    topology.status = receipt.resolution

    if receipt.resolution in {Resolution.CLOSED_HIGHER, Resolution.CLOSED_TO_OPENING}:
        axiometry.admitted[topology.topology_id] = receipt
        axiometry.open_candidates.pop(topology.topology_id, None)
    elif receipt.resolution is Resolution.REFUSED:
        axiometry.refused[topology.topology_id] = receipt
        axiometry.open_candidates.pop(topology.topology_id, None)
    elif receipt.resolution is Resolution.FALSE_COLLAPSE:
        axiometry.false_collapses[topology.topology_id] = receipt
        axiometry.open_candidates.pop(topology.topology_id, None)

    # Attach motif reference without treating motif list as topology identity.
    receipt.evidence.setdefault("unified_axiometry", axiometry.originless_relation)
    receipt.evidence.setdefault(
        "motifs_are_not_topology_catalog",
        True,
    )
    return receipt


def construct_next_topos(
    axiometry: UnifiedAxiometry,
    parent: VerificationTopology,
    *,
    topology_id: str,
    basis_cycle: dict[str, Any],
    closure_cycle: dict[str, Any],
) -> VerificationTopology:
    """Generator step: from an admitted topology, construct a further candidate topos."""
    parent_receipt = axiometry.admitted.get(parent.topology_id)
    if parent_receipt is None or parent_receipt.resolution not in {
        Resolution.CLOSED_HIGHER,
        Resolution.CLOSED_TO_OPENING,
    }:
        raise ValueError("next topos requires an admitted parent topology")
    child = VerificationTopology(
        topology_id=topology_id,
        basis_cycle=basis_cycle,
        closure_cycle=closure_cycle,
        ball_perspective={"parent": parent.topology_id, **parent.ball_perspective},
        hair_perspective=dict(parent.hair_perspective),
        encoding_topos=dict(parent.encoding_topos),
        relation_topos=dict(parent.relation_topos),
        openings=["further_layer"],
    )
    axiometry.open_candidates[topology_id] = child
    return child


# --- Backward-compatible names (deprecated semantics: motifs ≠ fixed topologies) ---

TopologyConstraint = DerivationMotif
ADMISSIBLE_TOPOLOGIES = UNIFIED_AXIOMETRY_MOTIFS  # legacy alias: motifs, not a topology catalog


def assert_admissible(policy: dict[str, Any]) -> list[str]:
    """Check that a policy does not invert the unified axiometry into a fixed catalog.

    Treating topologies as a closed fixed list, or scores as identity, is a violation.
    """
    violations: list[str] = []
    if policy.get("treat_score_as_identity"):
        violations.append("axiometry_is_shadow:violated")
    if policy.get("allow_reordered_support_as_same_path"):
        violations.append("ordered_support_identity:violated")
    if policy.get("flatten_biological_modalities"):
        violations.append("biological_nonidentical_recovery:violated")
    if policy.get("topologies_are_fixed_catalog"):
        violations.append("generator_not_totality:violated")
    if policy.get("require_predeclared_topology_ids"):
        violations.append("topologies_admitted_in_resolution:violated")
    return violations


def default_admissibility_policy() -> dict[str, Any]:
    return {
        "unified_axiometry": "C",
        "topologies_are_fixed_catalog": False,
        "require_predeclared_topology_ids": False,
        "treat_score_as_identity": False,
        "allow_reordered_support_as_same_path": False,
        "flatten_biological_modalities": False,
        "derivation_motifs": [m.motif_id for m in UNIFIED_AXIOMETRY_MOTIFS],
        "epistemic_status": "DESIGN DERIVATION",
    }
